### ISSUE TITLE
Add option for notes to be destroyed after period of time

### ISSUE THREAD

**Issue by joshterrill** [joshterrill/hushnote#1]
Currently the only option to send notes is to send them via a link, once they are read, they are destroyed. It would be nice to be able to have an option to either let a user send a once-read-destroy note, or have a note that remains on the link for a specified period of time, and then gets destroyed. The once-read-destroy note should be selected by default, but can be overwritten for the other option.

**Comment by masquel** [comment]
I'll watch this

**Comment by joshterrill** [comment]
Fixed in https://github.com/joshterrill/hushnote/pull/3
