### ISSUE TITLE
Use client-side encryption

### ISSUE THREAD

**Issue by Cologler** [joshterrill/hushnote#9]
Server-side encryption is not safe because the owner of the server can read the content of the note.

## Currently

1. User `POST` plain text to `/create` to create a note, return URL `/read/<noteid>/<password>`.
1. Webpage shows `/read/<noteid>/<password>` on the user screen.

## Expected

1. User encrypts the plain text to encrypted text with `<password>`, the password won't be sent to the server.
1. User `POST` encrypted text to `/create` to create a note, return URL `/read/<noteid>`.
1. Webpage builds the note URL to `/read/<noteid>#<password>` and shows it on the user screen.

Now all encryption is on the client-side, even the owner of the server cannot read the content of the note.

**Comment by joshterrill** [comment]
If you'd like to submit a pull request, I'm happy to review it. Otherwise, I won't be able to get to something like this for some time. This was just a small side project that I created for myself to send messages to friends.

**Comment by ririko5834** [comment]
Good idea

**Comment by joshterrill** [comment]
Finally got around to this. Using the web UI, client-side encryption and decryption is now used instead of server-side.
